# Site settings
title: Portfolio
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Daniel Lepszy
user_description: My responsibilities involves mainly developing automated tests for web applications. I have been concentrated to develop CI / CD methodology by supplying smoke and integrations tests. Objected programming technique is familiar to me as the TDD. I am looking for the new opportunity to work in project regarding web applications.  
user_title: Test Automation Engineer
email: daniel.lepszy@gmail.com
twitter_username: lorem_ipsum
github_username:  DanielLepszy
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
